sudo: required
language: java
jdk:
  - oraclejdk11
services:
  - docker
script:
  - bash build.sh
after_success:
  - git add -f build/libs/application.jar  
deploy:
  skip_cleanup: true
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "review"
  env: "review-dev"
  bucket_name: "elasticbeanstalk-ap-southeast-1-413765782488"
  bucket_path: "review-dev"
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^release\/.*$	  
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
